/// Flutter icons Custom_Icon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Custom_Icon
///      fonts:
///       - asset: fonts/Custom_Icon.ttf
///
///
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Custom_Icon {
  Custom_Icon._();

  static const _kFontFam = 'Custom_Icon';
  static const String? _kFontPkg = null;

  static const IconData edit =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fitness_center =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData food =
      IconData(0xf0f5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon =
      IconData(0xf186, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blogger =
      IconData(0xf37c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData seedling =
      IconData(0xf4d8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cookie =
      IconData(0xf563, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_meatball =
      IconData(0xf73b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData egg =
      IconData(0xf7fb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
